global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'My GP server Metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8090']
        labels:
          application: 'My Spring Boot Application'
    basic_auth:
      username: 'actuator'
      password: 'actuatorPWD'